CRITICAL - 2022-02-08 05:56:40 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 05:58:39 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 05:59:40 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('3')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 06:05:26 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('3')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 06:05:31 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('9')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 06:07:01 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('9')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 06:07:02 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('9')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 06:07:02 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('9')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 06:07:32 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 08:27:26 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 08:27:51 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 08:27:54 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 08:32:15 --> Invalid file: edit-user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit-user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit-user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit-user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 08:39:40 --> Invalid file: edit-user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit-user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit-user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit-user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('7')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-02-08 08:54:08 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('10')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-02-08 10:52:52 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-08 10:52:52 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 C:\xampp\htdocs\code4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\code4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\code4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\code4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('carl.abregoso@g...', 'email', Array, NULL)
#4 C:\xampp\htdocs\code4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'carl.abregoso@g...', Array, Array)
#5 C:\xampp\htdocs\code4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\code4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SignupController->store()
#8 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#9 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-02-08 10:52:54 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-08 10:52:54 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 C:\xampp\htdocs\code4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\code4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\code4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\code4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('carl.abregoso@g...', 'email', Array, NULL)
#4 C:\xampp\htdocs\code4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'carl.abregoso@g...', Array, Array)
#5 C:\xampp\htdocs\code4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\code4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SignupController->store()
#8 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#9 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-02-08 10:53:42 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-08 10:53:42 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 C:\xampp\htdocs\code4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\code4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\code4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\code4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('carl.abregoso@g...', 'email', Array, NULL)
#4 C:\xampp\htdocs\code4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'carl.abregoso@g...', Array, Array)
#5 C:\xampp\htdocs\code4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\code4\app\Controllers\SignupController.php(27): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SignupController->store()
#8 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SignupController))
#9 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-02-08 11:03:12 --> Invalid file: edit_user.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('edit_user', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\UserCrud.php(35): view('edit_user', Array)
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\UserCrud->singleUser('10')
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
